### ISSUE TITLE
User Story: Thicken a cylinder

### ISSUE THREAD

**Issue by tomwillis608** [tomwillis608/thicker-stl#1]
As a TTRPG Miniature 3d printing enthusiast, 
so that I can ensure the integrity of thin parts in the model while preserving its overall shape,
I want to thicken an STL file representing a cylinder (with radius 1 unit and height 2 units) by applying a simple thickening algorithm.

### Terminal-based User Interface:

The user will interact with the application through a simple command-line interface (CLI).
No graphical UI is required.

### Clean and Screaming Architecture:

The core business logic (thickening algorithm) will be separate from the application’s I/O (file reading/writing), UI (CLI), and external libraries (which should be wrapped in humble objects).
The domain (STL file manipulation) and use cases (thickening logic) should be clearly separated.

### YAGNI (You Aren’t Gonna Need It):

- Focus only on the essential functionality to thicken the cylinder model. Don’t add features like advanced configurations, multi-format support, or GUI elements at this stage.
- Avoid over-engineering and unnecessary dependencies.

### Test-Driven Development (TDD):

Write tests before implementation.
100% test coverage is required for all parts of the code that are not humble objects or machine-generated.

### Unit Test Coverage:

The core functionality of the thickening algorithm, file handling, and model parsing will be thoroughly tested.
Only the minimal set of tests for the functionality will be written first (in line with YAGNI).

###  Input File:

The user provides an STL file for a cylinder with a radius of 1 unit and height of 2 units (the test file is created and stored in tests/fixtures/).
The STL file is correctly read and parsed by the application.

### Thickening Process:

The application applies a thickening algorithm that modifies the geometry of the STL file, making the object thicker in all directions perpendicular to its primary axis (for the cylinder, this means the radius will increase, but the height remains the same).
The algorithm preserves the general shape of the cylinder without distorting the structure.

### Output File:

The thickened STL file is written to the disk, and its geometry is updated while maintaining the original file format.
The output STL file is stored in a designated directory (e.g., outputs/).

### Validation:

After running the tool, the thickened STL file can be opened in an STL viewer, and the shape should be visibly thicker but still retain the cylinder's overall proportions.
There is no visible change to the height, only the radius has increased.

### Test Coverage:

100% unit test coverage is applied for the thickening functionality (excluding humble objects and auto-generated code). Tests should cover:

- Proper parsing of the original STL file.
- Application of the thickening logic.
- Correct output generation and file writing.
- The tests should be written first and the implementation should be validated against them.

### No Unnecessary Complexity:

The solution is simple, only implementing the necessary functionality to meet the above criteria.
No additional features (such as file format support beyond STL, advanced CLI options, or optimization) are included at this stage.

#### Task 1.1: Set Up the Project Structure

- [x] Set up the directory structure according to clean architecture and screaming architecture principles:

- thicker/ for business logic and core functionality
- tests/ for test cases, including test data and utilities
- docs/ for ADRs and project documentation
- Create the initial README.md file with high-level project goals.

#### Task 1.2: Initialize Version Control and CI/CD

- [x] Set up Git repository.
- [x]  Initialize continuous integration (CI) configuration (e.g., GitHub Actions, Travis CI) to run tests and linting on push/PR.
- [ ] 
- [x]  Configure code quality checks (e.g., ruff for linting, pytest for testing).

#### Task 1.3: Define the First ADR

- [x] Write an ADR for the decision to use STL file format, including alternatives considered.

### 2A Task: Implement Unity Transformation
- [x] Objective: Implement a transformation that outputs the STL file exactly as it was, serving as a placeholder for future transformations.

Steps to Implement
Domain Layer:

Create a module thicker/domain/transformations.py.
Define a function or class for the unity transformation:
python
Copy code
def unity_transformation(mesh):
    """A transformation that returns the input mesh unmodified."""
    return mesh
Use Case Layer:

Update or create a use case thicker/use_cases/apply_transformation.py that:
Loads an STL file.
Applies the unity transformation.
Saves the unmodified STL to a specified output path.
Example:
python
Copy code
def apply_transformation(input_path, output_path, transformation):
    mesh = load_mesh(input_path)
    transformed_mesh = transformation(mesh)
    save_mesh(transformed_mesh, output_path)
Use humble objects to handle STL loading and saving.
Tests:

Write tests to validate:
The unity transformation does not modify the mesh.
The use case successfully loads, transforms, and saves an STL file.
Use the test cylinder STL file to verify correctness.
CLI Integration:

Update the CLI to allow the user to invoke this transformation.
Add arguments for input and output file paths.
Constraints
Ensure all components (transformation, use case, CLI) follow clean architecture principles.
Use TDD: Write the test cases for the unity transformation and use case before implementing them.
Use the domain layer for the transformation logic and humble objects for STL operations.

#### Task 2.1: Create the Domain Model for 3D meshes

- [x] Implement a class to represent a 3D mesh of vertices and faces in the domain/ folder.

#### Task 2.1.a: Create adapter for reading 3D mesh files into vertices and faces
- [x]  Define methods for extracting faces and vertices from 3D file readers

#### Task 2.1.b: Create a concrete adapter or humble object for reading 3D meshes from STL files
- [x] Define methods for reading and writing STL files, ensuring separation of concerns between business logic and file I/O.

#### Task 2.2: Implement Thickening Algorithm

- [x] Implement the basic thickening logic for a cylindrical STL file.
  - [x] Unity method
  - [x] Spherical thickening
  - [x] Cylindrical thickening
- [x] Ensure that the thickening happens perpendicular to the main axis of the cylinder, increasing the radius but keeping the height fixed.

#### Task 2.3: Test the Thickening Logic

- [x] Write unit tests for the thickening algorithm in test_thickening_service.py.
- [x] Test the algorithm with a simple cylinder STL file to verify it behaves as expected.

#### Task 3.1: Write Utility to Read STL File

- [x] Create a humble object in the infrastructure/ layer to handle reading STL files.
- [x] Use an existing library or implement the reading logic for STL files.

#### Task 3.2: Write Utility to Write STL File

- [x] Create a humble object in the infrastructure/ layer to handle writing the thickened STL file back to disk.

#### Task 4.1: Create CLI Command

- [x] Implement a simple command-line interface (CLI) using Python’s `argparse` or similar library to accept user input.

The CLI should accept an input STL file, apply the thickening process, and output a new STL file.

#### Task 4.2: Test the CLI

- [x] Write tests for the CLI functionality, ensuring the tool can be executed from the command line and produces the correct output.

#### Task 5.1: Review/Write Unit Tests

- [x] Ensure 100% test coverage for:

- Reading and parsing STL files.
- Applying the thickening algorithm.
- Writing the thickened STL file.

- [x] Use `pytest` to run tests and ensure no failures.

#### Task 5.2: Generate Test Cylinder STL File

- [x] Write a utility in the `tests/utils/` folder to generate a basic test STL file for the cylinder with a radius of 1 unit and height of 2 units. https://github.com/tomwillis608/thicker-stl/pull/3 

#### Task 5.3: Test with the Generated STL

- [x] Use the test cylinder STL file in tests/fixtures/ to verify that the tool thickens the model correctly.

#### Task 5.4: Review Code and Perform Code Quality Checks

- [x] Perform manual code review to ensure it meets coding standards.
- [x] Run ruff for linting and pytest for testing.
- [x] Ensure code is clear, well-documented, and adheres to best practices.

#### Task 6.1: Update Documentation

Update README.md to include:

- [x] How to install and run the tool.
- [x] Example usage (e.g., running the CLI).
- [x] Project goals and approach.
- [x] Add an ADR for any architectural decisions made during the implementation.

#### Task 6.2: Prepare for Final Review and Merge

- [x] Ensure all acceptance criteria are met.
- [x] Confirm that all tests pass.
- [x] Merge the code into the main branch.

## Definition of Done

- [x] Meet the acceptance criteria met
- [x] 100% test coverage
- [x] Architecture is screaming
- [x] Code quality and code security checks pass
- [x] Code refactored for clarity
- [x] Code reviewed by external agents
- [x] Followed the Dependency Rule
- [x] Merge code into main branch
- [x] Pass accessibility tests (manual and automatic)
- [x] Refactor code to current understanding
- [x] Tech debt eliminated to current understanding of domain
- [x] UI passes QA 
- [x] Updated build process as needed
- [x] Updated documentation including decision records as needed
- [x] Updated performance tests as needed
