### ISSUE TITLE
User Story: Remove flat spot at top of thickened figures

### ISSUE THREAD

**Issue by tomwillis608** [tomwillis608/thicker-stl#12]
As a TTRPG Miniature 3d printing enthusiast, 
so that I can make the top of the thickened figure preserve overall shape,
I want to thicken an STL file without having a flat spot near the z-axis for the highest vertices.

## Examples:

Here is a sample figurine to thicken, a basic elf:

![image](https://github.com/user-attachments/assets/5cd9b886-1793-4a97-8f0d-6172c2d8e392)

Here is the same elf after a thickening offset of 1:

![image](https://github.com/user-attachments/assets/e0843d38-1ba8-4af7-976d-a04ea1efebfd)

Here with offset of 2:

![image](https://github.com/user-attachments/assets/2360729e-273d-4276-a4bc-dfbf6dca5219)

Here with offset  of 5:

![image](https://github.com/user-attachments/assets/a07bbf0f-adc9-4e2f-aff8-9aeb46d4ed84)

You can see that the flat spot gets bigger with a larger offset, both at the top and on the base.  This story is only concerned with the flat spot at the top, but if the base is fixed by the updated code, that is a bonus.

## Constraints:

- Try to retain the general cylindrical nature of the transformation while eliminating the flat spot at the top.
- Apply all of the engineering and architectural constraints of the first user story throughout this project.

## Acceptance Criteria:

~~- [ ] Tests exist to detect a flat spot near the top of the figure for vertices close to the x-axis.~~
- [x] Visual inspection indicates the flat spot problem has been resolved.

## Tasks
~~- [ ] Write an end-to-end test to detect the flat spot artifact in a test fixture file.~~ I was unable to create this test. 
- [x] Add hemispherical-cylindrical thickening transformation
- [x] Add use case that calls the new transformation
- [x] Call the new use case from the CLI
- [x] Visually inspect results to satisfaction  

## Definition of Done

- [x] Meet the acceptance criteria met
- [x] 100% test coverage
- [x] Architecture is screaming
- [x] Code quality and code security checks pass
- [x] Code refactored for clarity
- [x] Code reviewed by external agents
- [x] Followed the Dependency Rule
- [x] Merge code into main branch
- [x] Pass accessibility tests (manual and automatic)
- [x] Refactor code to current understanding
- [x] Tech debt eliminated to current understanding of domain
- [x] UI passes QA 
- [x] Updated build process as needed
- [x] Updated documentation including decision records as needed
- [x] Updated performance tests as needed

**Comment by tomwillis608** [comment]
Another progression of 0, 1, 2, 3, 5 and 10 offsets. Notice that the highest points on the z-axis at low values for x,y are not at the very top of the figure, because the head is hunched forward.

![image](https://github.com/user-attachments/assets/f30bf69e-fffe-4d3c-a04b-a3986ae75bc7)

**Comment by tomwillis608** [comment]
Current plan- adjust purely cylindrical transformation to include a hemispherical top.
