### ISSUE TITLE
User Story: Keep the base out of the cylinder calculations

### ISSUE THREAD

**Issue by tomwillis608** [tomwillis608/thicker-stl#15]
As a table top figure FDM printer,
So that the thickening transformation is related to the figure and not the base,
I want the base excluded from the cylinder radius calculations.

Many of the figures we want to thicken with the application have a wide base, wider than the cylinder bounding the figure, such as this elf:

![image](https://github.com/user-attachments/assets/ce07076d-1951-43c8-b4fa-abe80cf0444c)

Automatically exclude this base from the cylinder radius calculation so that the radius is not overestimated.

## Tasks

- [x] Determine heuristic base height to exclude. We can start with 19%, based on work in #17
    - [x] Add a utility to analyze figurine STL files and calculate the maximum radius at various heights. This data is used to inform a heuristic for base height, documented in ADR 011. #17 
    - [x] Chose the initial heuristic base height value. Could be a fraction of overall height or a physical measurement, like 2 mm. Report it *here*. We can start with 19%, based on work in #17
- [x] Adjust main thickening use case to take the base-height-to-exclude into account when determining hemispherical radius for the transformation. #24
